stages:
  - prepare
  - test
  - clean

prepare:
  tags:
    - docker
  artifacts:
    paths:
      - venv
    expire_in: 20 minutes
  stage: prepare
  script:
    - yum -y install python39 python39-pip
    - echo running on $HOST as $USER
    - python3.9 -m venv venv
    - source venv/bin/activate
    - pip3.9 install -e .[all]
    - pip3.9 install pylint

test:
  tags:
    - docker
  stage: test
  script:
    - yum -y install python39 python39-pip
    - source venv/bin/activate
    - pytest --cov-report xml --cov-report term-missing --cov=one_pass tests/
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  # These artifacts are saved with every build in GitLab and can be reviewed later. If
  # we have a folder with HTML files, as in this example, users can navigate with their
  # browser.
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

<<<<<<< HEAD
=======
clean:
  tags:
    - docker
  stage: clean
  script:
    - echo Cleaning up
    - deactivate
    - rm -rf venv/
>>>>>>> e2bfcca (changes for docker #8)
