stages:
  - prepare
  - test
  - clean

cache:
  paths:
    - coverage/coverage.xml

prepare:
  tags:
    - docker
  artifacts:
    paths:
      - venv
  stage: prepare
  script:
    - yum install python39 python39-pip
    - echo running on $HOST as $USER
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install -e .[all]

test:
  tags:
    - docker
  stage: test
  script:
    - source venv/bin/activate
    - pytest --cov-report xml --cov-report term-missing --cov=one_pass tests/
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  # These artifacts are saved with every build in GitLab and can be reviewed later. If
  # we have a folder with HTML files, as in this example, users can navigate with their
  # browser.
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

clean:
  tags:
    - docker
  stage: clean
  script:
    - deactivate
    - rm -rf venv/
