stat: "bias_correction"
percentile_list : None,
threshold_exceed : None.
stat_freq: "daily"
output_freq: "daily"
time_step: 60 # timestep of data in minutes
param: "uas"
save: True
checkpoint: True
checkpoint_filepath: "/home/bsc32/bsc32263/git/data/"
out_filepath: "/home/bsc32/bsc32263/git/data/"
