---
# input file for mean OPA 

##### GENERAL INPUTS 

meanFreq: 'daily' # frequency of the statistic 
timeStep: 60 # this the timestep in MINUTES known from the MARS request 
var: 'vas' # if the file has many variables, this might be different in reality 
save: 'true' # do you want the output in memory or as a netCDF 
saveFreq: 'daily' # frequency at which to output netCDF of calculated statistics 

#### DATA INPUTS #### -eventually this will be from the GSV interface 
filePath: '/esarchive/scratch/alacima/projects/destination_earth/icon/tas-uas-vas-ngc2009_atm_2d_1h_inst_20200501T000000Z_5km.nc' # this has already been re-gridded onto regular lat / lon grid

### DATA OUTPUTS ### - where you want to the files to go (if you wave them saved anywhere)
filePathSave: '/esarchive/scratch/kgrayson/git/one_pass/'



