name: env_opa
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - xarray
  - dask
  - zarr
  - pytest
  - netcdf4
  - cytoolz
  - tqdm
  - sphinx
  - sphinx-rtd-theme
  - pip:
    - pytdigest
