name: env_opa
channels:
  - conda-forge
dependencies:
  - python>3.8
  - numpy
  - xarray
  - dask
  - zarr
  - pytest
  - netcdf4
  - cytoolz
  - tqdm
  - sphinx
  - sphinx-rtd-theme
  - cython
  - pip
  - pyarrow
  - pip:
    - -e .[all]


