name: "Container build and publish"

on:
  release:
    types: [published]
  # push: # We remove this to create the container only when we create a release from browser (issue #490)
  #   tags:
  #     - v*

env:
  IMAGE_NAME: one-pass
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
       packages: write
       contents: read
    steps:
      - name: "Check out code"
        uses: actions/checkout@v3
      - name: "Log in to registry"
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }}  --password-stdin
      - name: "build container"
        run: docker build --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}" .
      - name: "publish container"
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          [ "$VERSION" == "main" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
